---
# tasks file for ansible-role-jetbrains-toolbox

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ ansible_system }}.yml"

- name: Install JetBrains Toolbox
  ansible.builtin.include_tasks: "setup-{{ base_os[ansible_system] | default('Linux-Unix') }}.yml"
