---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: linux
    image: ${namespace:-diodonfrost}/${image:-ansible-ubuntu:20.04}
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/fuse:/dev/fuse
provisioner:
  name: ansible
verifier:
  name: ansible
