---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | JetBrains Toolbox should be installed
      ansible.builtin.stat:
        path: ~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
      register: stat_result

    - name: Verify commands outputs
      assert:
        that:
          - stat_result.stat.exists
        success_msg: "All tests passed"
