name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - rockylinux:8
          - centos:8
          - centos:7
          - fedora:35
          - fedora:34
          - fedora:33
          - fedora:32
          - fedora:31
          - fedora:30
          - ubuntu:20.04
          - ubuntu:18.04
          - debian:11
          - debian:10
          - opensuse:leap
          - archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Test Ansible role
        run: molecule test
        env:
          image: ansible-${{ matrix.image }}

      - name: Test Ansible role with check_mode enable
        run: molecule check
        env:
          image: ansible-${{ matrix.image }}
